// This file is generated by Slice Machine. Update with care!

import FirstComponent from './FirstComponent';
import Text from './Text';

export {
	FirstComponent,
	Text,
};

export const components = {
	first_component: FirstComponent,
	text: Text,
};
